formatter: "md doc" # this is required

version: ""

header-from: "main.tf"
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show:
    - all

content: |-
  {{ .Header }}
  # Clumio BYOK Terraform Module

  Terraform module to install the Clumio required AWS BYOK resources in the customer AWS account.

  ## Usage:
  This module is to be used along with the resource clumio_wallet as some of the inputs for the module are obtained from the output of clumio_wallet  resource.
  Below is an example of using the module:

  ```hcl
  {{ include "examples/all_data_sources/provider.tf" }}

  {{ include "examples/all_data_sources/main.tf" }}
  ```
  In the above example, since the regions in which the replica keys will be installed is based on the regions returned by the clumio_wallet resource, it has to be created first: `terraform apply -target clumio_wallet.test_wallet`.
  Once the wallet resource is created, the rest of the resources can be created using `terraform apply`.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
